In [3]:
from typing import Any

import cv2
import numpy as np
import func
import math

In [5]:
refPath = 'refImage.jpg'
imagePath2 = 'sample.jpg'
print(type(imagePath2))
# <class 'numpy.ndarray'>

print(imagePath2)
print(type(imagePath2))


# Create window with freedom of dimensions
cv2.namedWindow("finalImg",cv2.WINDOW_NORMAL)
imgR = cv2.imread(imagePath2)
img = cv2.imread(refPath)
# Use camera resolution
ims=cv2.resize(imgR ,(3264,2448))
cv2.imshow("finalImg" , ims)



#ref image for calibration
img , corners ,length, pixelRatio =func.cameraCalibration(img)

#applying the mouse event
#imgR = cv2.resize(imgR,(0,0),None,0.6,0.6)
# imgR NEED TO REPLACE AS ims
finalImg = cv2.imshow('finalImg',imgR)

def mouse_click(event, x, y, flags, param):
    #define the points array
    # to check if left mouse
    # button was clicked
    if event == cv2.EVENT_LBUTTONDOWN:
        #draw a circle
        cv2.circle(finalImg, (x,y),1,(0,0,255),2)
        #save the coordinates in points of array
        points.append((x,y))
        #connect with line
        if len(points) == 4:
          #imgR need to replaced as ims
          cv2.line(imgR,points[0],points[1],(0,0,255),2)
          cv2.line(imgR,points[2],points[3],(0,0,255),2)
         #font for left click event
        print(x, ',',y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY =str(x) + ',' + str(y)
        #All the imgR replace as ims
        cv2.putText(imgR, strXY, (x, y),font, 1, (255, 255, 0),2)
        cv2.imshow('finalImg', imgR)
        [x1, y1] = points[0]
        [x2, y2] = points[1]
        [x3, y3] = points[2]
        [x4, y4] = points[3]
        print(points[0])
        print(points[1])
        print(points[2])
        print(points[3])
        print('x1 :', x1, ',', 'y1 :', y1)
        print('x2 :', x2, ',', 'y2 :', y2)
        print('x3 :', x3, ',', 'y3 :', y3)
        print('x4 :', x4, ',', 'y4 :', y4)
        lengthArc1 = math.sqrt((math.pow((x1 - x2),2) + math.pow((y1 - y2),2)))
        print('Pixel ratio:',pixelRatio )
        print('Saddle_Height:',(lengthArc1*pixelRatio))
        lengthArc2 = math.sqrt((math.pow((x3 - x4), 2) + math.pow((y3 - y4), 2)))
        print('Pixel ratio:', pixelRatio)
        print('Reach:', (lengthArc2 * pixelRatio))


       #print(type(lengthArc.item()))

points = []

cv2.setMouseCallback('finalImg', mouse_click)




cv2.waitKey(0)
cv2.destroyAllWindows() 



<class 'str'>
sample.jpg
<class 'str'>
[[170 244]]
[[197 242]]
[[188 101]]
[[161 105]]
x2 : 197 , y2 : 242
x3 : 188 , y3: 101
<class 'numpy.float64'>
<class 'float'>
length : 141.28694207179942
<class 'numpy.float64'>
<class 'float'>
Pixel_ratio:  0.3538897456963215
834 , 826


IndexError: list index out of range

2359 , 702


IndexError: list index out of range

1210 , 1924


IndexError: list index out of range

889 , 826
(834, 826)
(2359, 702)
(1210, 1924)
(889, 826)
x1 : 834 , y1 : 826
x2 : 2359 , y2 : 702
x3 : 1210 , y3 : 1924
x4 : 889 , y4 : 826
Pixel ratio: 0.3538897456963215
Saddle_Height: 541.4629914639944
Pixel ratio: 0.3538897456963215
Reach: 404.835793671572
